/* This file is automatically generated. DO NOT EDIT! */

#ifndef _butter_h
#define _butter_h


/* Implementation is inspired by D. Hale and J.F. Claerbout, 1983, Butterworth
 * dip filters: Geophysics, 48, 1033-1038. */
    
#include "rsf.h"


typedef struct Butter *butter;
/* abstract data type */


butter butter_init(bool low     /* low-pass (or high-pass) */, 
		   float cutoff /* cut off frequency */, 
		   int nn       /* number of poles */);
/*< initialize >*/


void butter_close(butter bw);
/*< Free allocated storage >*/


void butter_apply (const butter bw, int nx, float *x /* data [nx] */);
/*< filter the data (in place) >*/

#endif
