/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_intsinc8_h
#define _sf_intsinc8_h


#include <rsf.h>


void ints8c (int nxin         /* number of x values at which y(x) is input */, 
	     float dxin       /* x sampling interval for input y(x) */, 
	     float fxin       /* x value of first sample input */, 
	     sf_complex *yin  /* [nxin] array of input y(x) values:  yin[0] = y(fxin), etc. */,
	     sf_complex yinl  /* value used to extrapolate yin values to left of yin[0] */, 
	     sf_complex yinr  /* value used to extrapolate yin values to right of yin[nxin-1] */, 
	     int nxout        /* number of x values a which y(x) is output */, 
	     float *xout      /* [nxout] array of x values at which y(x) is output */, 
	     sf_complex *yout /* [nxout] array of output y(x):  yout[0] = y(xout[0]), etc. */);
/*< Interpolation of a uniformly-sampled complex function y(x) via a
table of 8-coefficient sinc approximations; maximum error for frequiencies
less than 0.6 nyquist is less than one percent.

Because extrapolation of the input function y(x) is defined by the
left and right values yinl and yinr, the xout values are not restricted
to lie within the range of sample locations defined by nxin, dxin, and
fxin. >*/


void ints8r (int nxin /* number of x values at which y(x) is input */, 
	     float dxin /* x sampling interval for input y(x) */, 
	     float fxin /* x value of first sample input */, 
	     float *yin /* [nxin] array of input y(x) values:  yin[0] = y(fxin), etc. */, 
	     float yinl  /* value used to extrapolate yin values to left of yin[0] */, 
	     float yinr  /* alue used to extrapolate yin values to right of yin[nxin-1] */, 
	     int nxout   /* number of x values a which y(x) is output */, 
	     float *xout /* [nxout] array of x values at which y(x) is output */, 
	     float *yout /* [nxout] array of output y(x):  yout[0] = y(xout[0]), etc. */);
/*< Interpolation of a uniformly-sampled real function y(x) via a
table of 8-coefficient sinc approximations; maximum error for frequiencies
less than 0.6 nyquist is less than one percent.

Because extrapolation of the input function y(x) is defined by the
left and right values yinl and yinr, the xout values are not restricted
to lie within the range of sample locations defined by nxin, dxin, and
fxin. >*/

#endif
