/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_inttable8_h
#define _sf_inttable8_h


void intt8c (int ntable       /* number of tabulated interpolation operators; ntable>=2 */, 
	     float table[][8] /* array of tabulated 8-point interpolation operators */,
	     int nxin         /* number of x values at which y(x) is input */, 
	     float dxin       /* x sampling interval for input y(x) */, 
	     float fxin       /* x value of first sample input */, 
	     sf_complex *yin  /* array of input y(x) values:  yin[0] = y(fxin), etc. */,
	     sf_complex yinl  /* value used to extrapolate yin values to left of yin[0] */, 
	     sf_complex yinr  /* value used to extrapolate yin values to right of yin[nxin-1] */, 
	     int nxout        /* number of x values at which y(x) is output */, 
	     float *xout      /* x values a which y(x) is output */, 
	     sf_complex *yout /* array of output y(x) values:  yout[0] = y(xout[0]), etc. */);
/*< interpolation of a uniformly-sampled complex function y(x)
  via a table of 8-coefficient interpolators 

  The table of interpolation operators must be as follows:

Let d be the distance, expressed as a fraction of dxin, from a particular
xout value to the sampled location xin just to the left of xout.  Then,
for d = 0.0,

table[0][0:7] = 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0

are the weights applied to the 8 input samples nearest xout.
Likewise, for d = 1.0,

table[ntable-1][0:7] = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0

are the weights applied to the 8 input samples nearest xout.  In general,
for d = (float)itable/(float)(ntable-1), table[itable][0:7] are the
weights applied to the 8 input samples nearest xout.  If the actual sample
distance d does not exactly equal one of the values for which interpolators
are tabulated, then the interpolator corresponding to the nearest value of
d is used.

Because extrapolation of the input function y(x) is defined by the left
and right values yinl and yinr, the xout values are not restricted to lie
within the range of sample locations defined by nxin, dxin, and fxin. >*/


void intt8r (int ntable       /* number of tabulated interpolation operators; ntable>=2 */, 
	     float table[][8] /* array of tabulated 8-point interpolation operators */,
	     int nxin         /* number of x values at which y(x) is input */, 
	     float dxin       /* x sampling interval for input y(x) */, 
	     float fxin       /* x value of first sample input */, 
	     float *yin       /* array of input y(x) values:  yin[0] = y(fxin), etc. */,
	     float yinl       /* value used to extrapolate yin values to left of yin[0] */, 
	     float yinr       /* value used to extrapolate yin values to right of yin[nxin-1] */, 
	     int nxout        /* number of x values at which y(x) is output */, 
	     float *xout      /* x values at which y(x) is output */, 
	     float *yout      /* array of output y(x) values:  yout[0] = y(xout[0]), etc. */);
/*< interpolation of a uniformly-sampled complex function y(x)
  via a table of 8-coefficient interpolators 

  The table of interpolation operators must be as follows:

Let d be the distance, expressed as a fraction of dxin, from a particular
xout value to the sampled location xin just to the left of xout.  Then,
for d = 0.0,

table[0][0:7] = 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0

are the weights applied to the 8 input samples nearest xout.
Likewise, for d = 1.0,

table[ntable-1][0:7] = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0

are the weights applied to the 8 input samples nearest xout.  In general,
for d = (float)itable/(float)(ntable-1), table[itable][0:7] are the
weights applied to the 8 input samples nearest xout.  If the actual sample
distance d does not exactly equal one of the values for which interpolators
are tabulated, then the interpolator corresponding to the nearest value of
d is used.

Because extrapolation of the input function y(x) is defined by the left
and right values yinl and yinr, the xout values are not restricted to lie
within the range of sample locations defined by nxin, dxin, and fxin. >*/

#endif
