/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sf_sinc_h
#define _sf_sinc_h


float fsinc (float x);
/*< Return sinc(x) = sin(PI*x)/(PI*x) (float version) >*/


double dsinc (double x);
/*< Return sinc(x) = sin(PI*x)/(PI*x) (double version) >*/

#endif
